### ISSUE TITLE
Remove setup.py?

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/ga4gh-common#11]
`ga4gh_common/setup.py` does consolidate setup code across the repos, but importing it in each repo's `setup.py` requires that `ga4gh_common` is installed as a package before the other package is installed, which is not always true and can cause an install to fail.  Which is more important, consolidating setup code or guaranteeing a normal pip install pattern?

**Comment by reece** [comment]
I recommend against importing another setup.py within a package's own setup.py. It won't work in contexts where ga4gh_common isn't already installed.

One alternative is to use ga4gh_common as a template and manually sync changes between repos. This creates an incentive to package-specific details in configuration files, such as setup.cfg. I do this with [my python template package](https://github.com/reece/pytemplate) and it works okay.

Another option is to use [PBR](http://docs.openstack.org/developer/pbr/#setup-py), which puts everything in a config file. (I don't use PBR because I want to also sync a bunch of other files (see pytemplate above), so it wouldn't save me effort.)

**Comment by dcolligan** [comment]
Thanks for the info, @reece 

Yes, I'm leaning towards taking out the import since we want to not break pip semantics and ensure a path of least resistance for (new) users.  Unfortunately, this will resort in code duplication, but I don't see any way around that.

PBR looks like it solves different problems than the ones we have.  I want to eliminate redundancy in `setup.py` files across different ga4gh repositories.  PBR looks like it only operates within one repository.  (But perhaps we could use PBR to reduce some of the boilerplate code...)

(I suppose we could utilize a different project structure that united all of our code into one giant repository, but I don't see a need for doing that -- indeed, there are many drawbacks.  But in that case, the problem I am trying to solve would not come up in the first place.)

**Comment by dcolligan** [comment]
Fixed in #12
